# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.9.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    - name: Change directory to backend
      run: cd backend
    - name: Install dependencies
      run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
    - name: Create .env file
      run: |
        touch .env
        echo "{{ secrets.BACKEND_ENV }}" > .env
